version: '3'
services:
  admin:
    image: authjanitor.functions.adminapi
  agent:
    image: authjanitor.functions.agent
  client:
    image: authjanitor.aspnet.adminui    
    ports: 
      - "8080:80"